prompt --install
@@application/set_environment.sql
@@application/delete_application.sql
@@application/create_application.sql
@@application/user_interfaces.sql
@@application/shared_components/navigation/lists/navigation_menu.sql
@@application/shared_components/navigation/lists/navigation_bar.sql
@@application/shared_components/navigation/listentry.sql
@@application/shared_components/files/icons_app_icon_32_png.sql
@@application/shared_components/files/icons_app_icon_144_rounded_png.sql
@@application/shared_components/files/icons_app_icon_192_png.sql
@@application/shared_components/files/icons_app_icon_256_rounded_png.sql
@@application/shared_components/files/icons_app_icon_512_png.sql
@@application/plugin_settings.sql
@@application/shared_components/security/authorizations/administration_rights.sql
@@application/shared_components/navigation/navigation_bar.sql
@@application/shared_components/logic/application_settings.sql
@@application/shared_components/navigation/tabs/standard.sql
@@application/shared_components/navigation/tabs/parent.sql
@@application/shared_components/user_interface/lovs/employee_details_t3_employee_name.sql
@@application/shared_components/user_interface/lovs/meal_manager_t3_meal_manager_code.sql
@@application/shared_components/user_interface/lovs/t3_products_product_name.sql
@@application/shared_components/user_interface/lovs/t3_products_product_name1.sql
@@application/shared_components/user_interface/lovs/t3_products_product_name2.sql
@@application/shared_components/user_interface/lovs/uom_code.sql
@@application/shared_components/user_interface/lovs/uom_code1.sql
@@application/pages/page_groups.sql
@@application/comments.sql
@@application/shared_components/navigation/breadcrumbs/breadcrumb.sql
@@application/shared_components/navigation/breadcrumbentry.sql
@@application/shared_components/user_interface/templates/label/required_floating.sql
@@application/shared_components/user_interface/templates/popuplov.sql
@@application/shared_components/user_interface/themes.sql
@@application/shared_components/user_interface/theme_style.sql
@@application/shared_components/user_interface/theme_files.sql
@@application/shared_components/user_interface/template_opt_groups.sql
@@application/shared_components/user_interface/template_options.sql
@@application/shared_components/globalization/language.sql
@@application/shared_components/globalization/translations.sql
@@application/shared_components/logic/build_options.sql
@@application/shared_components/globalization/messages.sql
@@application/shared_components/globalization/dyntranslations.sql
@@application/shared_components/security/authentications/oracle_apex_accounts.sql
@@application/user_interfaces/combined_files.sql
@@application/pages/page_00000.sql
@@application/pages/page_00001.sql
@@application/pages/page_00002.sql
@@application/pages/page_00008.sql
@@application/pages/page_00009.sql
@@application/pages/page_00014.sql
@@application/pages/page_00015.sql
@@application/pages/page_00018.sql
@@application/pages/page_00019.sql
@@application/pages/page_00026.sql
@@application/pages/page_00027.sql
@@application/pages/page_00039.sql
@@application/pages/page_00041.sql
@@application/pages/page_00042.sql
@@application/pages/page_00049.sql
@@application/pages/page_00050.sql
@@application/pages/page_00081.sql
@@application/pages/page_00082.sql
@@application/pages/page_00083.sql
@@application/pages/page_00084.sql
@@application/pages/page_00085.sql
@@application/pages/page_00086.sql
@@application/pages/page_00087.sql
@@application/pages/page_00088.sql
@@application/pages/page_00089.sql
@@application/pages/page_00187.sql
@@application/pages/page_09999.sql
@@application/deployment/definition.sql
@@application/deployment/checks.sql
@@application/deployment/buildoptions.sql
@@application/end_environment.sql
